version: '3.8'

volumes:
  mysql_data:
      driver: local
  redis_data:
      driver: local

networks:
  apifort:
    external: true

services:
  gateway:
    build:
      context: '.'
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_LOG_LEVEL: INFO
      QUARKUS_REDIS_HOSTS: redis://redis:6379
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://book-club-db:3306/api-fort-schema?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: root
      QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      #QUARKUS_GRPC_SERVER_HOST: api-fort-kc-service
      #QUARKUS_GRPC_SERVER_PORT: 9001
      QUARKUS_GRPC_CLIENTS__PUBLICACCESSSERVICE__HOST: api-fort-kc-service
      QUARKUS_GRPC_CLIENTS__PUBLICACCESSSERVICE__PORT: 9000
      APIFORT_ADMIN_PUBLIC_CERTIFICATE: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz18hpIK6nddBKVS7XDtTZyZwMWx2q03PMvHptzTXTSYSwjipSxVURMebGE8H1oTiitg5UYhttVMzRoGcHUu41OhfijSpQBbbXP9XcCXJoIxW8+JcQ6RodLRKJ0vx80Uy0+AMgQeTNXQ575SGrigdMrBrKH/79GZ6U8cF8h9QMFyVriYHixlqEy+WRrZnuFAqNIwOW360AZzMrwYxUVQtsXVO7AKIVfNR4qs4LetWBQcSvlyTanAiWDrVCIL7Fen/lsM2s0Svr0E13vQKOpc3jhQ7JnK0VfWaZoDwuo3Li1vGHvXlt0pJ7Dfva9SBu8syCtuKD5Dbo8Od0ggIxpXYdQIDAQAB'
    ports:
      - 8080:8080
    networks:
      - apifort
    depends_on:
      - mysql
  api-fort-kc-service:
    image: quarkus/api-fort-admin-jvm:latest
    environment:
      QUARKUS_PROFILE: 'book-club'
      KEYCLOAK_ADMIN_REALM_CLIENT_ID_SECRET: 'w6iLSb9FgBUEYwBj75wtkTaYn1WuRYie'
      QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    ports:
      - 8080
      - 9000
    networks:
      - apifort
  redis:
    image: redis:7.0.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - apifort
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - apifort
  keycloak:
    build:
      context: './omni-ops-kc'
      dockerfile: Dockerfile
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      KC_DB_URL_PORT: 3306
      #KC_DB_URL_PROPERTIES: "connectTimeout=30000"
    ports:
      - 8180:8080
    depends_on:
      - mysql
    command: ["start-dev", "--import-realm"]
    networks:
      - apifort
  book-club:
    image: book-club:latest
    ports:
      - '8085:8080'
    environment:
      QUARKUS_HTTP_CORS_ORIGINS: 'http://localhost:8080'
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:otel:mysql://book-club-db:3306/library'
      QUARKUS_DATASOURCE_USERNAME: 'root'
      QUARKUS_DATASOURCE_PASSWORD: 'root'
    networks:
      - apifort
